CREATE DATABASE IF NOT EXISTS wp;
CREATE USER IF NOT EXISTS 'qcherel'@'%' IDENTIFIED BY 'user42';
GRANT ALL PRIVILEGES ON wp.* TO 'qcherel'@'%';
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY 'root42';
